[package]
name = "test_runner"
version = "0.1.0"
authors = ["alex <hortinstein@gmail.com>"]
edition = "2018"

[dependencies]
term = "*"
difference = "2.0"
rustc-test = "0.3.0"
toml = "0.4"
serde_derive = "1.0"
serde = "1.0"
path_abs = "*"
walkdir = "2.2.7"